/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.factura;
import java.awt.event.KeyEvent;
import ec.edu.ups.controladores.ControladorFactura;
import ec.edu.ups.controladores.ControladorFacturaDetallada;
import ec.edu.ups.controladores.ControladorCitaMedica;
import ec.edu.ups.modelo.Factura;
import ec.edu.ups.modelo.FacturaDetallada;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author tians
 */
public class VentanaAnularFactura extends javax.swing.JInternalFrame {
private ControladorCitaMedica controladorCitaMedica;
    private ControladorFactura controladorFactura;
    private ControladorFacturaDetallada controladorFacturaDetallada;
    private Locale localizacion;
    private static ResourceBundle mensajes;
    public static DefaultTableModel modelo;
    /**
     * Creates new form VentanaAnularFactura
     */
    public VentanaAnularFactura(ControladorCitaMedica controladorCitaMedica, ControladorFactura controladorFactura, ControladorFacturaDetallada controladorFacturaDetallada) {
        initComponents();
        initComponents();
        this.controladorCitaMedica = controladorCitaMedica;
        this.controladorFactura = controladorFactura;
        this.controladorFacturaDetallada = controladorFacturaDetallada;
        modelo = new DefaultTableModel();
        txtCodigoF.setEnabled(true);
    }
    public static void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", Locale.getDefault());
        lblMenuEliminarF.setText(mensajes.getString("anular.factura"));
        lblcodigo.setText(mensajes.getString("codigo"));
        lbleliminar.setText(mensajes.getString("eliminar"));
        Object[] columnas = {mensajes.getString("cantidad"), mensajes.getString("codigo"), mensajes.getString("paciente"), mensajes.getString("medico"), mensajes.getString("fecha"), mensajes.getString("total")};
        modelo.setColumnIdentifiers(columnas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenuEliminarF = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        txtCodigoF = new javax.swing.JTextField();
        lblcodigo = new javax.swing.JLabel();
        btnAnular = new javax.swing.JButton();
        lbleliminar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblMenuEliminarF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblMenuEliminarF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuEliminarF.setText("ELIMINAR FACTURA");
        lblMenuEliminarF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Anulada", "Codigo", "Paciente", "Medico", "Fecha", "Total"
            }
        ));
        tblCitas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblCitasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblCitas);

        txtCodigoF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCodigoF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoF.setEnabled(false);

        lblcodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcodigo.setText("CÓDIGO");
        lblcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/eliminar.png"))); // NOI18N
        btnAnular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        lbleliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbleliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbleliminar.setText("ANULAR");
        lbleliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/buscar1.png"))); // NOI18N
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigoF, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(lblMenuEliminarF, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 229, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbleliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuEliminarF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(txtCodigoF, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbleliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCitasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCitasKeyReleased

    }//GEN-LAST:event_tblCitasKeyReleased

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        int codigoFactura = Integer.parseInt(txtCodigoF.getText());
        Factura factura=controladorFactura.read(codigoFactura);
        if (factura != null){
            factura.setAnulada(true);
            JOptionPane.showMessageDialog(null, "Factura Anulada");
        }else{
            JOptionPane.showMessageDialog(null, "La factura no existe");
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Busca la cita medica a traves del codigo
        int codigoFactura = Integer.parseInt(txtCodigoF.getText());
        Factura factura=controladorFactura.read(codigoFactura);
        if (factura != null){
            Set<FacturaDetallada> detalles=factura.getDetalles();
            DefaultTableModel modelo = (DefaultTableModel) tblCitas.getModel();
            for (FacturaDetallada facturas : detalles){
                Object[] datos= {factura.isAnulada(),
                    factura.getCodigo(),
                    facturas.getCitaMedica().getPaciente().getNombre(),
                    facturas.getCitaMedica().getMedico().getNombre(),
                    factura.getFecha(),
                    facturas.getCitaMedica().getPrecio()
                };
                modelo.addRow(datos);
            }
        }else{
            JOptionPane.showMessageDialog(null, "La factura no existe");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblMenuEliminarF;
    public static javax.swing.JLabel lblcodigo;
    public static javax.swing.JLabel lbleliminar;
    private javax.swing.JTable tblCitas;
    private javax.swing.JTextField txtCodigoF;
    // End of variables declaration//GEN-END:variables
}
