/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.receta;

import ec.edu.ups.controladores.ControladorCitaMedica;
import ec.edu.ups.controladores.ControladorCitaMedicaDetallada;
import ec.edu.ups.controladores.ControladorMedicina;
import ec.edu.ups.controladores.ControladorMedico;
import ec.edu.ups.controladores.ControladorPaciente;
import ec.edu.ups.controladores.ControladorReceta;
import ec.edu.ups.modelo.Receta;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Quezada Bryam
 */
public class VentanaListarRecetas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaListarRecetas
     */
    public static NuevoModelo modelo;
    private ControladorCitaMedica controladorCitaMedica;
    private ControladorCitaMedicaDetallada controladorCitaMedicaDetallada;
    private ControladorPaciente controladorPaciente;
    private ControladorMedico controladorMedico;
    private ControladorMedicina controladorMedicina;
    private ControladorReceta controladorReceta;
    private Locale localizacion;
    private static ResourceBundle mensajes;
    public VentanaListarRecetas(ControladorReceta controladorReceta, ControladorPaciente controladorPaciente, ControladorMedicina controladorMedicina,ControladorCitaMedica controladorCitaMedica, ControladorCitaMedicaDetallada controladorCitaMedicaDetallada) {
        initComponents();
        this.controladorReceta = controladorReceta;
        this.controladorMedicina = controladorMedicina;
        this.controladorCitaMedica = controladorCitaMedica;
        this.controladorCitaMedicaDetallada = controladorCitaMedicaDetallada;
        this.controladorPaciente = controladorPaciente;
        this.controladorMedico = controladorMedico;
        modelo = new NuevoModelo();        
        Object[] columnas = {"Codigo", "Paciente", "Cedula", "Direccion", "Telefono", "Médico", "Especialidad", "Numero Cita","Medicina","Marca","Precio","Indicaciones", "Fecha"};
        modelo.setColumnIdentifiers(columnas);
        tabla.setModel(modelo);

        llenarTabla();
    }
    public static void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", Locale.getDefault());
        Object[] columnas = {mensajes.getString("codigo"), mensajes.getString("paciente"), mensajes.getString("cedula"), mensajes.getString("direccion"), mensajes.getString("telefono"), mensajes.getString("medico"), mensajes.getString("especialidad"), mensajes.getString("numerocita"), mensajes.getString("medicina"), mensajes.getString("marca"), mensajes.getString("precio"), mensajes.getString("indicaciones"), mensajes.getString("fecha")};
        modelo.setColumnIdentifiers(columnas);
    }
     public void llenarTabla() {
        Set<Receta> Lista = controladorReceta.getLista();
        for (Receta receta : Lista) {
            Object[] datos = {receta.getCodigo(),
                receta.getPaciente().getNombre(),
                receta.getPaciente().getCedula(),
                receta.getPaciente().getDireccion(),
                receta.getPaciente().getTelefono(),
                receta.getCitaMedica().getMedico().getNombre(),
                receta.getCitaMedica().getMedico().getEspecialidad(),
                receta.getCitaMedica().getNumeroCita(),
                receta.getMedicina().getNombre(),
                receta.getMedicina().getMarca(),
                receta.getMedicina().getPrecio(),
                receta.getIndicaciones(),
                receta.getCitaMedica().getFechaCita()};
            modelo.addRow(datos);

        }
    }
/**
    *Metodo que hereda los datos del DefaulTableModel sirva para poder hacer editables o no las columnas
    */
    public class NuevoModelo extends DefaultTableModel{
    /**
     * Define la posibilidad de editar las columnas
     */    
    public final boolean [] TblColums= {false,false,false,false,false,false,false,false,false,false,false,false,false};

        @Override
        public boolean isCellEditable(int row, int column) {
            return this.TblColums[column];
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "PACIENTE", "CEDULA", "DIRECCION", "TELEFONO", "DOCTOR", "ESPECIALIDAD", "NUMERO CITA ", "MEDICINA", "MARCA", "PRECIO", "INDICACIONES", "FECHA"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
